### ISSUE TITLE
pip version is outdated

### ISSUE THREAD

**Issue by ctrlmaniac** [JRubics/poetry-publish#1]
Hi! pip version should be updated before running poetry!

```
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by JRubics** [comment]
Base image has been updated https://github.com/docker-library/python/commit/44ded7c92b0c20abbeaa88785751eb0822d05ced
