### ISSUE TITLE
v1.13 has old entrypoint.sh

### ISSUE THREAD

**Issue by BrianPugh** [JRubics/poetry-publish#24]
I just pulled the v1.13 docker image and inspected the contents. `entrypoint.sh` still has the old `poetry plugin add`, can you check it out and release a new version? Thank you so much!

**Comment by JRubics** [comment]
It should be fine now, sorry for the inconvenience, not sure how it happened :shrug: Thank you for the patience :slightly_smiling_face:

**Comment by BrianPugh** [comment]
works perfect now! Thank you!
