### ISSUE TITLE
Issue with File Permissions on dist/ files

### ISSUE THREAD

**Issue by travis-cook-sfdc** [JRubics/poetry-publish#28]
I'm working in a GitHub Enterprise environment that uses self-hosted machines to run github actions.  The github actions are run under a non-root `foo` user.  Because docker runs as a root / privileged user, the `dist/` files this action creates end up on the host machine with `root` permissions.  Then, when the action reruns, the `foo` user does not have permissions to checkout & cleanup the previously created files.

Some ideas I've had to try to resolve this but figure I'd raise the issue here:
- Have the action automatically clean up the `dist/` files from the shared volume regardless of success / failure status.
- Add an additional step to delete the docker volume prior to checkout.
- Add an argument to the action to have it transfer ownership of the `dist/` folder to `$userArgValue`

What do you think would make the most sense given the issue?

**Comment by travis-cook-sfdc** [comment]
Ah yeah - that makes a lot of sense to me.  I ended up using this action in order to clean up the directory: https://github.com/peter-murray/reset-workspace-ownership-action/blob/main/README.md

**Comment by JRubics** [comment]
Happy to hear you managed to solve the issue :tada:
