### ISSUE TITLE
Allow publish from subdirectory

### ISSUE THREAD

**Issue by nielstenboom** [JRubics/poetry-publish#31]
Hello!

I wanted to use this action to publish a package residing in a subdirectory, but I couldn't find a way to do this.

Would it be possible to add a like a `path` variable to the action from where the publish command will be called?

Thanks!

**Comment by JRubics** [comment]
Hey :slightly_smiling_face: 
I added it in release  v1.16 as `package_directory` variable, please let me know if this solves your issue :slightly_smiling_face:

**Comment by nielstenboom** [comment]
Wow that's really fast, thanks!

**Comment by JRubics** [comment]
You're welcome! :tada:
