### ISSUE TITLE
File name reuse

### ISSUE THREAD

**Issue by edcohen08** [JRubics/poetry-publish#35]
Hey! We're using v1.13 for our package and hitting an issue from pypi about file name reuse. I updated the pyproject.toml to have 
```version = "0.0.8"``` but in the workflow we have

```
Installing the current project: package (0.0.7)
Building package (0.0.7)
  - Building sdist
  - Built package-0.0.7.tar.gz
  - Building wheel
  - Built package-0.0.7-py3-none-any.whl
Using a plaintext file to store credentials

Publishing package (0.0.7) to PyPI
 - Uploading package-0.0.7-py3-none-any.whl 0%`
 - Uploading package-0.0.7-py3-none-any.whl 100%
 
HTTP Error 400: File already exists. See https://pypi.org/help/#file-name-reuse for more information. 
```

Wondering if I'm missing something?

**Comment by JRubics** [comment]
Hi, sorry for the late response.
Did you use `actions/checkout` before this step?

**Comment by edcohen08** [comment]
Hi, no worries!

Here's our publish workflow [https://github.com/Lightmatter/welkin-health/blob/85aa9b28e4c06a30eb575722342b74a0cda52c2a/.github/workflows/publish.yaml](https://github.com/Lightmatter/welkin-health/blob/85aa9b28e4c06a30eb575722342b74a0cda52c2a/.github/workflows/publish.yaml)

**Comment by edcohen08** [comment]
@JRubics whoooops thank you. That was totally my misunderstanding of releases and tags. Sorry to bother over this and really appreciate you taking that in depth of a look!

**Comment by JRubics** [comment]
Not a problem, happy to help! :tada:
