### ISSUE TITLE
Publish to a Github repo

### ISSUE THREAD

**Issue by RempelOliveira** [JRubics/poetry-publish#40]
I have a question about this package.  Is it possible to publish a package to a Github repository?

I'm looking for how to do this but I'm not finding an answer about it.

Can anyone help me with this?

**Comment by JRubics** [comment]
Hi,
I'm not sure if that's possible even manually. Can you please share some example so I can maybe help you?

**Comment by JRubics** [comment]
This issue is deprecated. Closing it
