### ISSUE TITLE
The action should use the --without dev notation

### ISSUE THREAD

**Issue by Pooouf** [JRubics/poetry-publish#46]
According to the documentation of poetry :
["The --no-dev option is now deprecated. You should use the --without dev notation instead."](https://python-poetry.org/docs/cli/#options-8)

**Comment by JRubics** [comment]
Hi,
Thank you for letting me know :pray: 
It's updated in the latest release - v2.0. You can now use it as:
`poetry_install_options: "--without dev"`
More details [here](https://github.com/JRubics/poetry-publish?tab=readme-ov-file#poetry_install_options).
