### ISSUE TITLE
Build fails because dev dependencies are not installed

### ISSUE THREAD

**Issue by jwg4** [JRubics/poetry-publish#5]
Hi there, my build using this action fails: https://github.com/jwg4/exact_cover/runs/1676582881?check_suite_focus=true because numpy is not present. Numpy is one of the configured dependencies in poetry. It is a build dep as well as an install dep.

I have a manual deploy action which runs 'poetry install' before running 'poetry build'. I think you need to do this in your entrypoint to resolve this issue.

**Comment by JRubics** [comment]
Hi, thank you a lot for reporting this issue, I fixed it, you can return to using the action now if you want.

**Comment by JRubics** [comment]
Done

**Comment by jwg4** [comment]
Thank you very much!
